// This file was automatically generated by genny.
// Any changes will be lost if this file is regenerated.
// see https://github.com/cheekybits/genny

package types

import (
	"fmt"

	"github.com/gkany/graphSDK/logging"
	"github.com/gkany/graphSDK/util"
	"github.com/juju/errors"
)

type ContractBinCodeID struct {
	ObjectID
}

func (p ContractBinCodeID) Marshal(enc *util.TypeEncoder) error {
	n, err := enc.EncodeUVarintByByte(uint64(p.Instance()))
	if err != nil {
		return errors.Annotate(err, "encode instance")
	}

	for i := 0; i < 8-n; i++ {
		if err := enc.EncodeUVarint(uint64(0)); err != nil {
			return errors.Annotate(err, "encode zero")
		}
	}

	return nil
}

func (p *ContractBinCodeID) Unmarshal(dec *util.TypeDecoder) error {
	var instance uint64
	if err := dec.DecodeUVarint(&instance); err != nil {
		return errors.Annotate(err, "decode instance")
	}

	p.number = UInt64((uint64(SpaceTypeProtocol) << 56) | (uint64(ObjectTypeContractBinCode) << 48) | instance)
	return nil
}

type ContractBinCodeIDs []ContractBinCodeID

func (p ContractBinCodeIDs) Marshal(enc *util.TypeEncoder) error {
	if err := enc.EncodeUVarint(uint64(len(p))); err != nil {
		return errors.Annotate(err, "encode length")
	}

	for _, ex := range p {
		if err := enc.Encode(ex); err != nil {
			return errors.Annotate(err, "encode ContractBinCodeID")
		}
	}

	return nil
}

func ContractBinCodeIDFromObject(ob GrapheneObject) ContractBinCodeID {
	id, ok := ob.(*ContractBinCodeID)
	if ok {
		return *id
	}

	p := ContractBinCodeID{}
	p.MustFromObject(ob)
	if p.ObjectType() != ObjectTypeContractBinCode {
		panic(fmt.Sprintf("invalid ObjectType: %q has no ObjectType 'ObjectTypeContractBinCode'", p.ID()))
	}

	return p
}

//NewContractBinCodeID creates an new ContractBinCodeID object
func NewContractBinCodeID(id string) GrapheneObject {
	gid := new(ContractBinCodeID)
	if err := gid.Parse(id); err != nil {
		logging.Errorf(
			"ContractBinCodeID parser error %v",
			errors.Annotate(err, "Parse"),
		)
		return nil
	}

	if gid.ObjectType() != ObjectTypeContractBinCode {
		logging.Errorf(
			"ContractBinCodeID parser error %s",
			fmt.Sprintf("%q has no ObjectType 'ObjectTypeContractBinCode'", id),
		)
		return nil
	}

	return gid
}
