// Code generated by "stringer -type=OperationType"; DO NOT EDIT.

package types

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[OperationTypeTransfer-0]
	_ = x[OperationTypeLimitOrderCreate-1]
	_ = x[OperationTypeLimitOrderCancel-2]
	_ = x[OperationTypeCallOrderUpdate-3]
	_ = x[OperationTypeFillOrder-4]
	_ = x[OperationTypeAccountCreate-5]
	_ = x[OperationTypeAccountUpdate-6]
	_ = x[OperationTypeAccountUpgrade-7]
	_ = x[OperationTypeAssetCreate-8]
	_ = x[OperationTypeAssetUpdate-9]
	_ = x[OperationTypeAssetUpdateRestricted-10]
	_ = x[OperationTypeAssetUpdateBitasset-11]
	_ = x[OperationTypeAssetUpdateFeedProducers-12]
	_ = x[OperationTypeAssetIssue-13]
	_ = x[OperationTypeAssetReserve-14]
	_ = x[OperationTypeAssetSettle-15]
	_ = x[OperationTypeAssetGlobalSettle-16]
	_ = x[OperationTypeAssetPublishFeed-17]
	_ = x[OperationTypeWitnessCreate-18]
	_ = x[OperationTypeWitnessUpdate-19]
	_ = x[OperationTypeProposalCreate-20]
	_ = x[OperationTypeProposalUpdate-21]
	_ = x[OperationTypeProposalDelete-22]
	_ = x[OperationTypeCommitteeMemberCreate-23]
	_ = x[OperationTypeCommitteeMemberUpdate-24]
	_ = x[OperationTypeCommitteeMemberUpdateGlobalParameters-25]
	_ = x[OperationTypeVestingBalanceCreate-26]
	_ = x[OperationTypeVestingBalanceWithdraw-27]
	_ = x[OperationTypeWorkerCreate-28]
	_ = x[OperationTypeBalanceClaim-29]
	_ = x[OperationTypeAssetSettleCancel-30]
	_ = x[OperationTypeAssetClaimFees-31]
	_ = x[OperationTypeBidCollateral-32]
	_ = x[OperationTypeExecuteBid-33]
	_ = x[OperationTypeContractCreate-34]
	_ = x[OperationTypeCallContractFunction-35]
	_ = x[OperationTypeTemporaryAuthorityChange-36]
	_ = x[OperationTypeRegisterNhAssetCreator-37]
	_ = x[OperationTypeCreateWorldView-38]
	_ = x[OperationTypeRelateWorldView-39]
	_ = x[OperationTypeCreateNhAsset-40]
	_ = x[OperationTypeDeleteNhAsset-41]
	_ = x[OperationTypeTransferNhAsset-42]
	_ = x[OperationTypeCreateNhAssetOrder-43]
	_ = x[OperationTypeCancelNhAssetOrder-44]
	_ = x[OperationTypeFillNhAssetOrder-45]
	_ = x[OperationTypeCreateFile-46]
	_ = x[OperationTypeAddFileRelateAccount-47]
	_ = x[OperationTypeFileSignature-48]
	_ = x[OperationTypeRelateParentFile-49]
	_ = x[OperationTypeReviseContract-50]
	_ = x[OperationTypeCrontabCreate-51]
	_ = x[OperationTypeCrontabCancel-52]
	_ = x[OperationTypeCrontabRecover-53]
	_ = x[OperationTypeUpdateCollateralForGas-54]
	_ = x[OperationTypeAccountAuthentication-55]
}

const _OperationType_name = "OperationTypeTransferOperationTypeLimitOrderCreateOperationTypeLimitOrderCancelOperationTypeCallOrderUpdateOperationTypeFillOrderOperationTypeAccountCreateOperationTypeAccountUpdateOperationTypeAccountUpgradeOperationTypeAssetCreateOperationTypeAssetUpdateOperationTypeAssetUpdateRestrictedOperationTypeAssetUpdateBitassetOperationTypeAssetUpdateFeedProducersOperationTypeAssetIssueOperationTypeAssetReserveOperationTypeAssetSettleOperationTypeAssetGlobalSettleOperationTypeAssetPublishFeedOperationTypeWitnessCreateOperationTypeWitnessUpdateOperationTypeProposalCreateOperationTypeProposalUpdateOperationTypeProposalDeleteOperationTypeCommitteeMemberCreateOperationTypeCommitteeMemberUpdateOperationTypeCommitteeMemberUpdateGlobalParametersOperationTypeVestingBalanceCreateOperationTypeVestingBalanceWithdrawOperationTypeWorkerCreateOperationTypeBalanceClaimOperationTypeAssetSettleCancelOperationTypeAssetClaimFeesOperationTypeBidCollateralOperationTypeExecuteBidOperationTypeContractCreateOperationTypeCallContractFunctionOperationTypeTemporaryAuthorityChangeOperationTypeRegisterNhAssetCreatorOperationTypeCreateWorldViewOperationTypeRelateWorldViewOperationTypeCreateNhAssetOperationTypeDeleteNhAssetOperationTypeTransferNhAssetOperationTypeCreateNhAssetOrderOperationTypeCancelNhAssetOrderOperationTypeFillNhAssetOrderOperationTypeCreateFileOperationTypeAddFileRelateAccountOperationTypeFileSignatureOperationTypeRelateParentFileOperationTypeReviseContractOperationTypeCrontabCreateOperationTypeCrontabCancelOperationTypeCrontabRecoverOperationTypeUpdateCollateralForGasOperationTypeAccountAuthentication"

var _OperationType_index = [...]uint16{0, 21, 50, 79, 107, 129, 155, 181, 208, 232, 256, 290, 322, 359, 382, 407, 431, 461, 490, 516, 542, 569, 596, 623, 657, 691, 741, 774, 809, 834, 859, 889, 916, 942, 965, 992, 1025, 1062, 1097, 1125, 1153, 1179, 1205, 1233, 1264, 1295, 1324, 1347, 1380, 1406, 1435, 1462, 1488, 1514, 1541, 1576, 1610}

func (i OperationType) String() string {
	if i >= OperationType(len(_OperationType_index)-1) {
		return "OperationType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _OperationType_name[_OperationType_index[i]:_OperationType_index[i+1]]
}
