// Code generated by "stringer -type=OperationType"; DO NOT EDIT.

package types

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[OperationTypeTransfer-0]
	_ = x[OperationTypeLimitOrderCreate-1]
	_ = x[OperationTypeLimitOrderCancel-2]
	_ = x[OperationTypeCallOrderUpdate-3]
	_ = x[OperationTypeFillOrder-4]
	_ = x[OperationTypeAccountCreate-5]
	_ = x[OperationTypeAccountUpdate-6]
	_ = x[OperationTypeAccountUpgrade-7]
	_ = x[OperationTypeAssetCreate-8]
	_ = x[OperationTypeAssetUpdate-9]
	_ = x[OperationTypeAssetUpdateRestricted-10]
	_ = x[OperationTypeAssetUpdateBitasset-11]
	_ = x[OperationTypeAssetUpdateFeedProducers-12]
	_ = x[OperationTypeAssetIssue-13]
	_ = x[OperationTypeAssetReserve-14]
	_ = x[OperationTypeAssetSettle-15]
	_ = x[OperationTypeAssetGlobalSettle-16]
	_ = x[OperationTypeAssetPublishFeed-17]
	_ = x[OperationTypeWitnessCreate-18]
	_ = x[OperationTypeWitnessUpdate-19]
	_ = x[OperationTypeProposalCreate-20]
	_ = x[OperationTypeProposalUpdate-21]
	_ = x[OperationTypeProposalDelete-22]
	_ = x[OperationTypeCommitteeMemberCreate-23]
	_ = x[OperationTypeCommitteeMemberUpdate-24]
	_ = x[OperationTypeCommitteeMemberUpdateGlobalParameters-25]
	_ = x[OperationTypeVestingBalanceCreate-26]
	_ = x[OperationTypeVestingBalanceWithdraw-27]
	_ = x[OperationTypeWorkerCreate-28]
	_ = x[OperationTypeBalanceClaim-29]
	_ = x[OperationTypeAssetSettleCancel-30]
	_ = x[OperationTypeAssetClaimFees-31]
	_ = x[OperationTypeBidCollateral-32]
	_ = x[OperationTypeExecuteBid-33]
	_ = x[OperationTypeAccountWhitelist-34]
	_ = x[OperationTypeAccountTransfer-35]
	_ = x[OperationTypeAssetFundFeePool-36]
	_ = x[OperationTypeWithdrawPermissionCreate-37]
	_ = x[OperationTypeWithdrawPermissionUpdate-38]
	_ = x[OperationTypeWithdrawPermissionClaim-39]
	_ = x[OperationTypeWithdrawPermissionDelete-40]
	_ = x[OperationTypeCustom-41]
	_ = x[OperationTypeAssert-42]
	_ = x[OperationTypeOverrideTransfer-43]
	_ = x[OperationTypeTransferToBlind-44]
	_ = x[OperationTypeBlindTransfer-45]
	_ = x[OperationTypeTransferFromBlind-46]
	_ = x[OperationTypeFBADistribute-47]
}

const _OperationType_name = "OperationTypeTransferOperationTypeLimitOrderCreateOperationTypeLimitOrderCancelOperationTypeCallOrderUpdateOperationTypeFillOrderOperationTypeAccountCreateOperationTypeAccountUpdateOperationTypeAccountUpgradeOperationTypeAssetCreateOperationTypeAssetUpdateOperationTypeAssetUpdateRestrictedOperationTypeAssetUpdateBitassetOperationTypeAssetUpdateFeedProducersOperationTypeAssetIssueOperationTypeAssetReserveOperationTypeAssetSettleOperationTypeAssetGlobalSettleOperationTypeAssetPublishFeedOperationTypeWitnessCreateOperationTypeWitnessUpdateOperationTypeProposalCreateOperationTypeProposalUpdateOperationTypeProposalDeleteOperationTypeCommitteeMemberCreateOperationTypeCommitteeMemberUpdateOperationTypeCommitteeMemberUpdateGlobalParametersOperationTypeVestingBalanceCreateOperationTypeVestingBalanceWithdrawOperationTypeWorkerCreateOperationTypeBalanceClaimOperationTypeAssetSettleCancelOperationTypeAssetClaimFeesOperationTypeBidCollateralOperationTypeExecuteBidOperationTypeAccountWhitelistOperationTypeAccountTransferOperationTypeAssetFundFeePoolOperationTypeWithdrawPermissionCreateOperationTypeWithdrawPermissionUpdateOperationTypeWithdrawPermissionClaimOperationTypeWithdrawPermissionDeleteOperationTypeCustomOperationTypeAssertOperationTypeOverrideTransferOperationTypeTransferToBlindOperationTypeBlindTransferOperationTypeTransferFromBlindOperationTypeFBADistribute"

var _OperationType_index = [...]uint16{0, 21, 50, 79, 107, 129, 155, 181, 208, 232, 256, 290, 322, 359, 382, 407, 431, 461, 490, 516, 542, 569, 596, 623, 657, 691, 741, 774, 809, 834, 859, 889, 916, 942, 965, 994, 1022, 1051, 1088, 1125, 1161, 1198, 1217, 1236, 1265, 1293, 1319, 1349, 1375}

func (i OperationType) String() string {
	if i >= OperationType(len(_OperationType_index)-1) {
		return "OperationType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _OperationType_name[_OperationType_index[i]:_OperationType_index[i+1]]
}
