// Code generated by ffjson <https://github.com/pquerna/ffjson>. DO NOT EDIT.
// source: fillnhassetorderoperation.go

package operations

import (
	"bytes"
	"encoding/json"
	"fmt"
	fflib "github.com/pquerna/ffjson/fflib/v1"
)

// MarshalJSON marshal bytes to json - template
func (j *FillNhAssetOrderOperation) MarshalJSON() ([]byte, error) {
	var buf fflib.Buffer
	if j == nil {
		buf.WriteString("null")
		return buf.Bytes(), nil
	}
	err := j.MarshalJSONBuf(&buf)
	if err != nil {
		return nil, err
	}
	return buf.Bytes(), nil
}

// MarshalJSONBuf marshal buff to json - template
func (j *FillNhAssetOrderOperation) MarshalJSONBuf(buf fflib.EncodingBuffer) error {
	if j == nil {
		buf.WriteString("null")
		return nil
	}
	var err error
	var obj []byte
	_ = obj
	_ = err
	buf.WriteString(`{ "order":`)

	{

		obj, err = j.Order.MarshalJSON()
		if err != nil {
			return err
		}
		buf.Write(obj)

	}
	buf.WriteString(`,"fee_paying_account":`)

	{

		obj, err = j.FeePayingAccount.MarshalJSON()
		if err != nil {
			return err
		}
		buf.Write(obj)

	}
	buf.WriteString(`,"seller":`)

	{

		obj, err = j.Seller.MarshalJSON()
		if err != nil {
			return err
		}
		buf.Write(obj)

	}
	buf.WriteString(`,"nh_asset":`)

	{

		obj, err = j.NHAsset.MarshalJSON()
		if err != nil {
			return err
		}
		buf.Write(obj)

	}
	buf.WriteString(`,"price_amount":`)
	fflib.WriteJsonString(buf, string(j.PriceAmount))
	buf.WriteString(`,"price_asset_id":`)

	{

		obj, err = j.PriceAssetID.MarshalJSON()
		if err != nil {
			return err
		}
		buf.Write(obj)

	}
	buf.WriteString(`,"price_asset_symbol":`)
	fflib.WriteJsonString(buf, string(j.PriceAssetSymbol))
	buf.WriteString(`,"expiration":`)

	{

		obj, err = j.Expiration.MarshalJSON()
		if err != nil {
			return err
		}
		buf.Write(obj)

	}
	buf.WriteByte(',')
	if j.Fee != nil {
		if true {
			/* Struct fall back. type=types.AssetAmount kind=struct */
			buf.WriteString(`"fee":`)
			err = buf.Encode(j.Fee)
			if err != nil {
				return err
			}
			buf.WriteByte(',')
		}
	}
	buf.Rewind(1)
	buf.WriteByte('}')
	return nil
}

const (
	ffjtFillNhAssetOrderOperationbase = iota
	ffjtFillNhAssetOrderOperationnosuchkey

	ffjtFillNhAssetOrderOperationOrder

	ffjtFillNhAssetOrderOperationFeePayingAccount

	ffjtFillNhAssetOrderOperationSeller

	ffjtFillNhAssetOrderOperationNHAsset

	ffjtFillNhAssetOrderOperationPriceAmount

	ffjtFillNhAssetOrderOperationPriceAssetID

	ffjtFillNhAssetOrderOperationPriceAssetSymbol

	ffjtFillNhAssetOrderOperationExpiration

	ffjtFillNhAssetOrderOperationFee
)

var ffjKeyFillNhAssetOrderOperationOrder = []byte("order")

var ffjKeyFillNhAssetOrderOperationFeePayingAccount = []byte("fee_paying_account")

var ffjKeyFillNhAssetOrderOperationSeller = []byte("seller")

var ffjKeyFillNhAssetOrderOperationNHAsset = []byte("nh_asset")

var ffjKeyFillNhAssetOrderOperationPriceAmount = []byte("price_amount")

var ffjKeyFillNhAssetOrderOperationPriceAssetID = []byte("price_asset_id")

var ffjKeyFillNhAssetOrderOperationPriceAssetSymbol = []byte("price_asset_symbol")

var ffjKeyFillNhAssetOrderOperationExpiration = []byte("expiration")

var ffjKeyFillNhAssetOrderOperationFee = []byte("fee")

// UnmarshalJSON umarshall json - template of ffjson
func (j *FillNhAssetOrderOperation) UnmarshalJSON(input []byte) error {
	fs := fflib.NewFFLexer(input)
	return j.UnmarshalJSONFFLexer(fs, fflib.FFParse_map_start)
}

// UnmarshalJSONFFLexer fast json unmarshall - template ffjson
func (j *FillNhAssetOrderOperation) UnmarshalJSONFFLexer(fs *fflib.FFLexer, state fflib.FFParseState) error {
	var err error
	currentKey := ffjtFillNhAssetOrderOperationbase
	_ = currentKey
	tok := fflib.FFTok_init
	wantedTok := fflib.FFTok_init

mainparse:
	for {
		tok = fs.Scan()
		//	println(fmt.Sprintf("debug: tok: %v  state: %v", tok, state))
		if tok == fflib.FFTok_error {
			goto tokerror
		}

		switch state {

		case fflib.FFParse_map_start:
			if tok != fflib.FFTok_left_bracket {
				wantedTok = fflib.FFTok_left_bracket
				goto wrongtokenerror
			}
			state = fflib.FFParse_want_key
			continue

		case fflib.FFParse_after_value:
			if tok == fflib.FFTok_comma {
				state = fflib.FFParse_want_key
			} else if tok == fflib.FFTok_right_bracket {
				goto done
			} else {
				wantedTok = fflib.FFTok_comma
				goto wrongtokenerror
			}

		case fflib.FFParse_want_key:
			// json {} ended. goto exit. woo.
			if tok == fflib.FFTok_right_bracket {
				goto done
			}
			if tok != fflib.FFTok_string {
				wantedTok = fflib.FFTok_string
				goto wrongtokenerror
			}

			kn := fs.Output.Bytes()
			if len(kn) <= 0 {
				// "" case. hrm.
				currentKey = ffjtFillNhAssetOrderOperationnosuchkey
				state = fflib.FFParse_want_colon
				goto mainparse
			} else {
				switch kn[0] {

				case 'e':

					if bytes.Equal(ffjKeyFillNhAssetOrderOperationExpiration, kn) {
						currentKey = ffjtFillNhAssetOrderOperationExpiration
						state = fflib.FFParse_want_colon
						goto mainparse
					}

				case 'f':

					if bytes.Equal(ffjKeyFillNhAssetOrderOperationFeePayingAccount, kn) {
						currentKey = ffjtFillNhAssetOrderOperationFeePayingAccount
						state = fflib.FFParse_want_colon
						goto mainparse

					} else if bytes.Equal(ffjKeyFillNhAssetOrderOperationFee, kn) {
						currentKey = ffjtFillNhAssetOrderOperationFee
						state = fflib.FFParse_want_colon
						goto mainparse
					}

				case 'n':

					if bytes.Equal(ffjKeyFillNhAssetOrderOperationNHAsset, kn) {
						currentKey = ffjtFillNhAssetOrderOperationNHAsset
						state = fflib.FFParse_want_colon
						goto mainparse
					}

				case 'o':

					if bytes.Equal(ffjKeyFillNhAssetOrderOperationOrder, kn) {
						currentKey = ffjtFillNhAssetOrderOperationOrder
						state = fflib.FFParse_want_colon
						goto mainparse
					}

				case 'p':

					if bytes.Equal(ffjKeyFillNhAssetOrderOperationPriceAmount, kn) {
						currentKey = ffjtFillNhAssetOrderOperationPriceAmount
						state = fflib.FFParse_want_colon
						goto mainparse

					} else if bytes.Equal(ffjKeyFillNhAssetOrderOperationPriceAssetID, kn) {
						currentKey = ffjtFillNhAssetOrderOperationPriceAssetID
						state = fflib.FFParse_want_colon
						goto mainparse

					} else if bytes.Equal(ffjKeyFillNhAssetOrderOperationPriceAssetSymbol, kn) {
						currentKey = ffjtFillNhAssetOrderOperationPriceAssetSymbol
						state = fflib.FFParse_want_colon
						goto mainparse
					}

				case 's':

					if bytes.Equal(ffjKeyFillNhAssetOrderOperationSeller, kn) {
						currentKey = ffjtFillNhAssetOrderOperationSeller
						state = fflib.FFParse_want_colon
						goto mainparse
					}

				}

				if fflib.SimpleLetterEqualFold(ffjKeyFillNhAssetOrderOperationFee, kn) {
					currentKey = ffjtFillNhAssetOrderOperationFee
					state = fflib.FFParse_want_colon
					goto mainparse
				}

				if fflib.SimpleLetterEqualFold(ffjKeyFillNhAssetOrderOperationExpiration, kn) {
					currentKey = ffjtFillNhAssetOrderOperationExpiration
					state = fflib.FFParse_want_colon
					goto mainparse
				}

				if fflib.EqualFoldRight(ffjKeyFillNhAssetOrderOperationPriceAssetSymbol, kn) {
					currentKey = ffjtFillNhAssetOrderOperationPriceAssetSymbol
					state = fflib.FFParse_want_colon
					goto mainparse
				}

				if fflib.EqualFoldRight(ffjKeyFillNhAssetOrderOperationPriceAssetID, kn) {
					currentKey = ffjtFillNhAssetOrderOperationPriceAssetID
					state = fflib.FFParse_want_colon
					goto mainparse
				}

				if fflib.AsciiEqualFold(ffjKeyFillNhAssetOrderOperationPriceAmount, kn) {
					currentKey = ffjtFillNhAssetOrderOperationPriceAmount
					state = fflib.FFParse_want_colon
					goto mainparse
				}

				if fflib.EqualFoldRight(ffjKeyFillNhAssetOrderOperationNHAsset, kn) {
					currentKey = ffjtFillNhAssetOrderOperationNHAsset
					state = fflib.FFParse_want_colon
					goto mainparse
				}

				if fflib.EqualFoldRight(ffjKeyFillNhAssetOrderOperationSeller, kn) {
					currentKey = ffjtFillNhAssetOrderOperationSeller
					state = fflib.FFParse_want_colon
					goto mainparse
				}

				if fflib.AsciiEqualFold(ffjKeyFillNhAssetOrderOperationFeePayingAccount, kn) {
					currentKey = ffjtFillNhAssetOrderOperationFeePayingAccount
					state = fflib.FFParse_want_colon
					goto mainparse
				}

				if fflib.SimpleLetterEqualFold(ffjKeyFillNhAssetOrderOperationOrder, kn) {
					currentKey = ffjtFillNhAssetOrderOperationOrder
					state = fflib.FFParse_want_colon
					goto mainparse
				}

				currentKey = ffjtFillNhAssetOrderOperationnosuchkey
				state = fflib.FFParse_want_colon
				goto mainparse
			}

		case fflib.FFParse_want_colon:
			if tok != fflib.FFTok_colon {
				wantedTok = fflib.FFTok_colon
				goto wrongtokenerror
			}
			state = fflib.FFParse_want_value
			continue
		case fflib.FFParse_want_value:

			if tok == fflib.FFTok_left_brace || tok == fflib.FFTok_left_bracket || tok == fflib.FFTok_integer || tok == fflib.FFTok_double || tok == fflib.FFTok_string || tok == fflib.FFTok_bool || tok == fflib.FFTok_null {
				switch currentKey {

				case ffjtFillNhAssetOrderOperationOrder:
					goto handle_Order

				case ffjtFillNhAssetOrderOperationFeePayingAccount:
					goto handle_FeePayingAccount

				case ffjtFillNhAssetOrderOperationSeller:
					goto handle_Seller

				case ffjtFillNhAssetOrderOperationNHAsset:
					goto handle_NHAsset

				case ffjtFillNhAssetOrderOperationPriceAmount:
					goto handle_PriceAmount

				case ffjtFillNhAssetOrderOperationPriceAssetID:
					goto handle_PriceAssetID

				case ffjtFillNhAssetOrderOperationPriceAssetSymbol:
					goto handle_PriceAssetSymbol

				case ffjtFillNhAssetOrderOperationExpiration:
					goto handle_Expiration

				case ffjtFillNhAssetOrderOperationFee:
					goto handle_Fee

				case ffjtFillNhAssetOrderOperationnosuchkey:
					err = fs.SkipField(tok)
					if err != nil {
						return fs.WrapErr(err)
					}
					state = fflib.FFParse_after_value
					goto mainparse
				}
			} else {
				goto wantedvalue
			}
		}
	}

handle_Order:

	/* handler: j.Order type=types.NHAssetOrderID kind=struct quoted=false*/

	{
		if tok == fflib.FFTok_null {

		} else {

			tbuf, err := fs.CaptureField(tok)
			if err != nil {
				return fs.WrapErr(err)
			}

			err = j.Order.UnmarshalJSON(tbuf)
			if err != nil {
				return fs.WrapErr(err)
			}
		}
		state = fflib.FFParse_after_value
	}

	state = fflib.FFParse_after_value
	goto mainparse

handle_FeePayingAccount:

	/* handler: j.FeePayingAccount type=types.AccountID kind=struct quoted=false*/

	{
		if tok == fflib.FFTok_null {

		} else {

			tbuf, err := fs.CaptureField(tok)
			if err != nil {
				return fs.WrapErr(err)
			}

			err = j.FeePayingAccount.UnmarshalJSON(tbuf)
			if err != nil {
				return fs.WrapErr(err)
			}
		}
		state = fflib.FFParse_after_value
	}

	state = fflib.FFParse_after_value
	goto mainparse

handle_Seller:

	/* handler: j.Seller type=types.AccountID kind=struct quoted=false*/

	{
		if tok == fflib.FFTok_null {

		} else {

			tbuf, err := fs.CaptureField(tok)
			if err != nil {
				return fs.WrapErr(err)
			}

			err = j.Seller.UnmarshalJSON(tbuf)
			if err != nil {
				return fs.WrapErr(err)
			}
		}
		state = fflib.FFParse_after_value
	}

	state = fflib.FFParse_after_value
	goto mainparse

handle_NHAsset:

	/* handler: j.NHAsset type=types.NHAssetID kind=struct quoted=false*/

	{
		if tok == fflib.FFTok_null {

		} else {

			tbuf, err := fs.CaptureField(tok)
			if err != nil {
				return fs.WrapErr(err)
			}

			err = j.NHAsset.UnmarshalJSON(tbuf)
			if err != nil {
				return fs.WrapErr(err)
			}
		}
		state = fflib.FFParse_after_value
	}

	state = fflib.FFParse_after_value
	goto mainparse

handle_PriceAmount:

	/* handler: j.PriceAmount type=string kind=string quoted=false*/

	{

		{
			if tok != fflib.FFTok_string && tok != fflib.FFTok_null {
				return fs.WrapErr(fmt.Errorf("cannot unmarshal %s into Go value for string", tok))
			}
		}

		if tok == fflib.FFTok_null {

		} else {

			outBuf := fs.Output.Bytes()

			j.PriceAmount = string(string(outBuf))

		}
	}

	state = fflib.FFParse_after_value
	goto mainparse

handle_PriceAssetID:

	/* handler: j.PriceAssetID type=types.AssetID kind=struct quoted=false*/

	{
		if tok == fflib.FFTok_null {

		} else {

			tbuf, err := fs.CaptureField(tok)
			if err != nil {
				return fs.WrapErr(err)
			}

			err = j.PriceAssetID.UnmarshalJSON(tbuf)
			if err != nil {
				return fs.WrapErr(err)
			}
		}
		state = fflib.FFParse_after_value
	}

	state = fflib.FFParse_after_value
	goto mainparse

handle_PriceAssetSymbol:

	/* handler: j.PriceAssetSymbol type=string kind=string quoted=false*/

	{

		{
			if tok != fflib.FFTok_string && tok != fflib.FFTok_null {
				return fs.WrapErr(fmt.Errorf("cannot unmarshal %s into Go value for string", tok))
			}
		}

		if tok == fflib.FFTok_null {

		} else {

			outBuf := fs.Output.Bytes()

			j.PriceAssetSymbol = string(string(outBuf))

		}
	}

	state = fflib.FFParse_after_value
	goto mainparse

handle_Expiration:

	/* handler: j.Expiration type=types.Time kind=struct quoted=false*/

	{
		if tok == fflib.FFTok_null {

		} else {

			tbuf, err := fs.CaptureField(tok)
			if err != nil {
				return fs.WrapErr(err)
			}

			err = j.Expiration.UnmarshalJSON(tbuf)
			if err != nil {
				return fs.WrapErr(err)
			}
		}
		state = fflib.FFParse_after_value
	}

	state = fflib.FFParse_after_value
	goto mainparse

handle_Fee:

	/* handler: j.Fee type=types.AssetAmount kind=struct quoted=false*/

	{
		/* Falling back. type=types.AssetAmount kind=struct */
		tbuf, err := fs.CaptureField(tok)
		if err != nil {
			return fs.WrapErr(err)
		}

		err = json.Unmarshal(tbuf, &j.Fee)
		if err != nil {
			return fs.WrapErr(err)
		}
	}

	state = fflib.FFParse_after_value
	goto mainparse

wantedvalue:
	return fs.WrapErr(fmt.Errorf("wanted value token, but got token: %v", tok))
wrongtokenerror:
	return fs.WrapErr(fmt.Errorf("ffjson: wanted token: %v, but got token: %v output=%s", wantedTok, tok, fs.Output.String()))
tokerror:
	if fs.BigError != nil {
		return fs.WrapErr(fs.BigError)
	}
	err = fs.Error.ToError()
	if err != nil {
		return fs.WrapErr(err)
	}
	panic("ffjson-generated: unreachable, please report bug.")
done:

	return nil
}
